### ISSUE TITLE
Support all OpenEDX instances

### ISSUE THREAD

**Issue by dattaz** [openzim/openedx#1]
There is a lot of openedx instance (https://github.com/edx/edx-platform/wiki/Sites-powered-by-Open-edX), some change their html so the scrapper can't deal with them.
Main target are edx and fun, but we need to have a easy way to add other instance

**Comment by rgaudin** [comment]
We need to support openedx at large, starting with https://mooc.phzh.ch/courses.

**Comment by kelson42** [comment]
@rgaudin What are the challenges here? Is that possible at all? I have the feeling this ticket might be impossible to fix, like it is phrased.

**Comment by rgaudin** [comment]
As discussed on Wed, it is not possible at the moment and we have a per instance config in the code.
We should try to make that parameters, as for mwoffliner so it's more flexible
