### ISSUE TITLE
Videos are misaligned

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#112]
Follow-up on #73 - there is a marker to align the video, but it still isn't.
![Capture d’écran 2020-08-17 à 14 33 31](https://user-images.githubusercontent.com/21675885/90396635-d9157600-e096-11ea-9218-db56a8aa6b80.png)

**Comment by Popolechien** [comment]
The above screenshot is on macOS but here a similar issue on android. The cookie warning can also be seen to be off.
![Screenshot_20200817_145434_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/90398482-ccdee800-e099-11ea-85ff-64674ae67204.jpg)

**Comment by rgaudin** [comment]
Can you open a separate ticket for the cookie message as this is different ?

**Comment by Popolechien** [comment]
@rgaudin yes I'm opening it right now.
