### ISSUE TITLE
adjectives --> list of words does not open

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#116]
Topic 1, Unit 2, step 1, task 1
![Adjectives](https://user-images.githubusercontent.com/69838934/90484199-27c61d00-e136-11ea-827e-dc65cefcfa78.JPG)

Before I continue with new issues, can you please give me a short feedback if you can open the attachment and if it is clear if I give feedback like this? thanks, d

**Comment by rgaudin** [comment]
@IPECORE yes, the screenshot is visible thank you.

**Comment by satyamtg** [comment]
@IPECORE this does work for me when using kiwix-serve with Chrome or Firefox. Could you please tell which ZIM are you using and on what platform?

**Comment by satyamtg** [comment]
This is also due to the same reason of running in Kiwix-JS. We have #120 for this. Closing it.
