### ISSUE TITLE
text on the bottom of the website 

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#118]
What does it mean? Cookies? It looks different on PC or smartphone
![text bottom](https://user-images.githubusercontent.com/69838934/90514086-f9116c00-e160-11ea-95da-0b014459db72.JPG)

**Comment by satyamtg** [comment]
@IPECORE could you please tell the platform/reader you're running the ZIM on? Because this is actually weird. Should not be displayed this way. It's the CSS/JS that we fetch from PHZH directly.

**Comment by satyamtg** [comment]
Closing for the same reason as #116. This is also due to running in Kiwix-JS. We shall discuss on a single Kiwix-JS related thread, which is #120 .
