### ISSUE TITLE
can the text not be safed in the field?

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#123]
Topic 9, Unit 1
but this is a question in general as there are many fields where the students could directly write into the course
![texts in the fields cannot be safed](https://user-images.githubusercontent.com/69838934/90622987-2f5cf300-e216-11ea-9932-91331973f8fa.JPG)

**Comment by satyamtg** [comment]
@IPECORE ZIM files are made for portability and currently we don't have a mechanism to save any sort of user data / progress after writing a ZIM file. That's the reason why we cannot save progress data in a ZIM.
