### ISSUE TITLE
arrow button leads to "unknown page"

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#124]
topic 9 - 1-3 - task 3
![topic 9 - 1 - 3 - task 3 - arrow button does not lead forward](https://user-images.githubusercontent.com/69838934/90635755-e44cdb00-e229-11ea-8fd3-752b666f495f.JPG)

**Comment by rgaudin** [comment]
Can you please be more explicit about:
* Where you were?
* What you clicked on?
* Where that lead you?
* Where you expected to land?

**Comment by satyamtg** [comment]
@IPECORE , I went on the same page and tested both the arrows at the bottom. They work fine. I checked on this page - http://tmp.kiwix.org:9991/phzh_core-english-one_en_2020-08_zimfarm/A/course/core-english-01/topic-9-my-interests-and-where-i-want-to-go/unit-1-different-jobs-around-me/step-3/index.html .
Could you please recheck and confirm?

What I found though is the rightwards arrow button leads to invalid link at the very end of the course and the left arrow button leads to invalid link at the very beginning of the course. Both these ar only applicable to the arrows at the bottom only. But what you pointed out in this very issue works fine.
