### ISSUE TITLE
topic 6, health, unit 1, step 2, task 2. drag and drop does not work

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#134]
I cannot drag and drop the food icons into the food pyramid
![drag_and_drop](https://user-images.githubusercontent.com/69838934/91178547-903c6d80-e6e5-11ea-92ad-b001ef4b3c4b.JPG)

**Comment by rgaudin** [comment]
Again, drag-and-drop feature is not supported. It might eventually be in the future, as mentioned in #122
