### ISSUE TITLE
windows open differently, only first one is correct

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#137]
the others, from Oil to Beverage open a too big window
![windows open differently](https://user-images.githubusercontent.com/69838934/91179921-6f751780-e6e7-11ea-8859-80416729341b.JPG)

**Comment by rgaudin** [comment]
@IPECORE, could you please be more specific with your tickets?

* Where it is happening exactly (you can share the online URL as well)
* What you expect
* What you get.

**Comment by satyamtg** [comment]
@IPECORE , the thing you are talking about is an iframe and we do not really have control over content from an iframe. The scraper tries to download it as much as possible, but full support for iframes cannot be guaranteed (at least at this point of time unless we have a generic enough solution to iframes).

**Comment by rgaudin** [comment]
Absolutely.

@IPECORE, this is a kiwix-serve specific issue. This is not show in other readers (iOS, desktop, android).

The workaround we have at the moment, is to add `partial=true` to the MIME type of iframes'HTML articles (`text/html` obviously). We can't do that in zimwriterfs-like mode (nor in plain zimwriterfs).
Once we move away from this mode, we could be able to set it and that annoying bar would not be shown.

**Comment by rgaudin** [comment]
Right. @IPECORE the pyramid behaves as in the online course. The only thing we could do is try to fix the icons
