### ISSUE TITLE
Incorrect styling

### ISSUE THREAD

**Issue by IPECORE** [openzim/openedx#140]
![dark background](https://user-images.githubusercontent.com/69838934/91182074-fd520200-e6e9-11ea-889a-5a4985c6cf47.JPG)

**Comment by rgaudin** [comment]
In [topic 6, unit 3, step 1](http://tmp.kiwix.org:9991/phzh_core-english-one_en_2020-08_zimfarm/A/course/core-english-01/topic-6-i-live-in-a-healthy-way/unit-3-the-risks-of-drugs-and-alcohol/step-1/index.html) the step background color is lost resulting in problem being shown on dark color over dark background

**Comment by kelson42** [comment]
@rgaudin @satyamtg Seems a bug to fix, isn’t it?
