### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#148]
Scraping of Arabic content yields left-to-right text whereas it normally should be right-to-left.
Some of the interface strings also remain in the default language (english or french)
![image](https://user-images.githubusercontent.com/21675885/93339788-48b08980-f82c-11ea-950c-0dae9fcd5a67.png)

There should be a selector in the scraper that allows for setting the correct language of the course and then adapt the interface correspondingly
![image](https://user-images.githubusercontent.com/21675885/93340148-b9f03c80-f82c-11ea-9318-2f71efd0767a.png)

**Comment by rgaudin** [comment]
What we need is:

* support for i18n of our UI, including LTR/LTR tags in templates
* translation in french (because it's easy and testable)
* translation in arabic (so we can test RTL properly)

**Comment by satyamtg** [comment]
I've done the translation thing in #149, And in a local version, I've handled the RTL thing on our CSS. However, since we scrape CSS from the instance for the rest of the course, we need to scrape the HTML and the CSS of the RTL version, which seems to be a bit of a problem here as the selection menu on the PHZH instance is not at all common across scrapers.

**Comment by satyamtg** [comment]
Okay, so it seems that the language selection is handled by a cookie in edX too, it's just the cookie name is different and selector is in profile settings. Also looking at [this](https://github.com/edx/edx-platform/blob/255583874f915ae818eb5d3e2642083926ad8352/lms/templates/widgets/footer-language-selector.html), I found out that the cookie thing is used across instances. It's just that some do have things customized, but it seems that we can support this (Though we would need to add different cookie names for different instances).

**Comment by rgaudin** [comment]
OK, let me know if there's any blocker arising along the way.
