### ISSUE TITLE
Videos do not play on Android

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#152]
On Core zim phzh_core-english-one_en_2020-09.zim on Android 9 the video does not play (sound is ok). Video plays with no problem whatsover on desktop.

![Screenshot_20200922_154747_org kiwix kiwixmobile](https://user-images.githubusercontent.com/21675885/93892276-a6414c00-fcec-11ea-8151-d4d64e4f10ca.jpg)

**Comment by rgaudin** [comment]
Video playing is [currently broken on android](https://github.com/kiwix/kiwix-android/issues/2347). Closing here.

**Comment by Popolechien** [comment]
I've tested on macOS and Windows and it does not work either. Should we reopen or is this a bug that binds them all?

**Comment by rgaudin** [comment]
Can you reproduce on kiwix-serve? URL ?

**Comment by Popolechien** [comment]
Kiwix serve is not available on my machine for some reason (see [#477](../../../kiwix/kiwix-desktop/issues/477))

**Comment by rgaudin** [comment]
OK, can you share the ZIM url ; I'll refresh the demo

**Comment by Popolechien** [comment]
https://download.kiwix.org/zim/.hidden/dev/phzh_core-greek-one_el_2020-09.zim

**Comment by rgaudin** [comment]
Thank you ; updated the online demo with this ZIM. reopened #145.
