### ISSUE TITLE
Missing videos

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#159]
Looks very much like #145 except that in this case it's for all three PHZH zims.
![Capture d’écran 2020-10-21 à 17 03 05](https://user-images.githubusercontent.com/21675885/96738821-68a11300-13bf-11eb-8b83-71fe96dc8aec.png)

**Comment by satyamtg** [comment]
This is not quite related to #145. I tested the download and encode process again. They work fine. It's because youtube_dl is throwing 429s. I checked all the logs, and all have the same thing. Launched https://farm.openzim.org/pipeline/5f9269226c97ec4f8563ed54 to see what's the current scenario.

**Comment by rgaudin** [comment]
<img width="1367" alt="Screen Shot 2020-10-23 at 09 31 18" src="https://user-images.githubusercontent.com/57929/96987474-977bce00-1512-11eb-8b63-90203f4c481e.png">

videos works in this run but still that blank space above it
