### ISSUE TITLE
Getting error while setting up openedx

### ISSUE THREAD

**Issue by 123survesh** [openzim/openedx#16]
Hi, I tried setting up openedx after cloning it. I followed the steps in the Read.me and I got errors while executing **pip install openedx2zim**

**The error was :** 
    regex_3/_regex.c:46:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Here is the copy of the terminal output I got
https://paste.ofcode.org/srVPdhyaBVRzrxxEn42uGi

I don't know what is missing or what I am doing wrong. Please help me out.

**Comment by kelson42** [comment]
@123survesh For some reason you do not have the Python dev files on your system (thought they were a dependency of pip)... Anyway you need to install the libpython dev files to allow a few Python module to compile properly.

**Comment by dattaz** [comment]
@123survesh take care, pip module isn't up to date. (no new release since long long time...I hope a new release, like a beta next week)
