### ISSUE TITLE
Scraper incorrectly labels zim language to English

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#165]
Just noticed that both PHZH OpenedX MOOCs in Arabic and Greek are labeled (and found) as English
https://farm.openzim.org/recipes/phzh_core-arabic-one
https://farm.openzim.org/recipes/phzh_core-greek-one

![Screenshot_20201126_165219](https://user-images.githubusercontent.com/21675885/100371964-e08ada80-3008-11eb-8c1a-92ec94f7825e.jpg)

See https://github.com/openzim/zimfarm/issues/563

**Comment by kelson42** [comment]
The ZIM metadata seems indeed wrong https://library.kiwix.org/phzh_core-arabic-one-test-zim_ar_2020-11/M/Language

**Comment by kelson42** [comment]
Not sure but he conf language is in ISO2.... maybe the error comes from that. See https://farm.openzim.org/recipes/phzh_core-arabic-one/config

**Comment by kelson42** [comment]
A proper oprion name should be --language

**Comment by rgaudin** [comment]
There is no language option, as mentioned in my first answer.
Locale is for the UI, not the content.

Not familiar enough with codebase to say whether it's possible/wanted to have a dual purpose language option or if we should have two separate ones.

**Comment by kelson42** [comment]
The UI should be in sync with the content.

**Comment by satyamtg** [comment]
just saw that's because of "eng" mistakenly being hardcoded in the code. Fixing.
