### ISSUE TITLE
Missing content on italian version of CORE

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#167]
I generated and downloaded https://mirror.download.kiwix.org/zim/mooc/phzh_core-italian-one_it_2022-01.zim which simply is the italian version of previous zim files. 
While the structure and videos are there, other written content fails to appear.
This is the content available on the source (Argomento 1 > Unità 1:A proposito di me):
![image](https://user-images.githubusercontent.com/21675885/148232131-9e070760-b96e-44c0-b23d-4076a4bd4921.png)

While this is the zim content:
![image](https://user-images.githubusercontent.com/21675885/148232226-7caa7c6b-d6a2-46d0-a145-74a8363e6555.png)

Tested on Kiwix-desktop 2.0.5

**Comment by rgaudin** [comment]
Changed recipe params
