### ISSUE TITLE
Get hint for problem xblocks

### ISSUE THREAD

**Issue by dattaz** [openzim/openedx#27]
Code to handle this is write inside blocks extractor for problem but commented because still fail to get it

**Comment by satyamtg** [comment]
@dattaz you were talking about [this](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/problem_with_hint.html) right? I couldn't find one on either edX or PHZH. I mean do you remember where you found a  course with these kind of hints? Like for now, with the fixed answer scraping, we do have all the content replaced inside the question body, which includes messages after answer submission.

**Comment by dattaz** [comment]
I don't think so, because adaptive hint depend on student answers, done on server side...
I think it was hint already available before any submission but I have no example sorry.

**Comment by rgaudin** [comment]
Closing this as this is not clear anymore. We can reopen or open a new ticket with proper (up to date) details.
