### ISSUE TITLE
Docker: AttributeError

### ISSUE THREAD

**Issue by richen604** [openzim/openedx#29]
Getting an error using your latest docker image.

`<myuser>:/mnt/c/zim$ docker run openzim/openedx openedx2zim 'https://courses.edx.org/courses/course-v1:CornellX+ENGR2000X+1T2018/info/' 'https://www.edx.org/' '<email>' --password='<password>'
INFO:root:Test (missing) bin
INFO:root:Testing connection
INFO:root:Your login is ok!
Traceback (most recent call last):
  File "/usr/local/bin/openedx2zim", line 52, in <module>
    run()
  File "/usr/local/bin/openedx2zim", line 43, in run
    mooc=Mooc(c,arguments["<course_url>"], arguments["--transcode2webm"], arguments["--ignore-unsupported-xblocks"], arguments["--lang"])
  File "/usr/local/lib/python3.6/dist-packages/openedxtozim/mooc.py", line 58, in __init__
    self.course_id=get_course_id(self.course_url, c.conf["course_page_name"], c.conf["course_prefix"], self.instance_url)
  File "/usr/local/lib/python3.6/dist-packages/openedxtozim/mooc.py", line 39, in get_course_id
    clean_id=clean_url.group(0)[len(instance_url+course_prefix):-len(course_page_name)]
AttributeError: 'NoneType' object has no attribute 'group'`

Could be a Python version issue or very easily incorrect syntax on my part, any help would be appreciated.

**Comment by kelson42** [comment]
any idea?

**Comment by dattaz** [comment]
Hello,
Try with this url: `https://courses.edx.org/courses/course-v1:CornellX+ENGR2000X+1T2018/course/`
Sorry for the not up-to-date readme :grimacing:

**Comment by richen604** [comment]
Works with the /course/ url, thanks for clarifying

**Comment by kelson42** [comment]
@dattaz Should we close that ticket or do we have something to improve here?

**Comment by dattaz** [comment]
Correction done in README, so i think it's OK
