### ISSUE TITLE
find a mooc to implement and test youtube video extract from html page

### ISSUE THREAD

**Issue by dattaz** [openzim/openedx#3]

**Comment by rgaudin** [comment]
@satyamtg isn't that the case with phzh ?

**Comment by satyamtg** [comment]
Yes. Indeed it is. And works for now.

**Comment by kelson42** [comment]
If we have found a mooc and this is a reference mooc for us, then we can probably close this ticket. If something does not work with Youtube videos, we should open a tocket.
