### ISSUE TITLE
Assess scraper state

### ISSUE THREAD

**Issue by satyamtg** [openzim/openedx#31]
As the readme suggests, this scraper aims at scraping mooc courses from any openedx instance. It basically makes us have courses in our ZIM format. So, first things first, we need to be enrolled in the course we want to offline in order to use this scraper. The following things are needed at least to run the scraper -
- course URL
- registered e-mail ID on the openedx instance
- password for your account (In case of edX, it'd be your edX mail ID and password)

The scraper scrapes something called blocks, of which the openedx instances are composed of. One can read the full xblocks documentation [here](https://edx.readthedocs.io/projects/xblock-tutorial/en/latest/#). In simple words, they are independent pieces of code that do small independent things. For example, there can be a xblock for voting, another for videos and so on. xblocks use python, and web technologies (HTML, CSS, JS). The best explanation can be found in the docs in the aforementioned link.

Our scraper downloads a JSON from the openedx instance and it has all the info regarding the xblocs that the course has. 

The main file is openedx2zim which basically receives all arguments and first authenticates you with your email id and password using the code in openedx2zim/connection.py
Then basically the scraper follows the 3 steps -
1. Download JSON and parse it creating a file structure similar to the hierarchy of the blocks
Here's a zipped and prettified version of the JSON for [this course](https://courses.edx.org/courses/course-v1:edX+edx201+1T2020/course/) - [Sample JSON files](https://github.com/openzim/openedx/files/4837039/api_responses.zip))

2. Annex
3. Download

So let's get into the 3 steps one by one. We pass the connection object we get after testing the connection to create a Mooc object. (See mooc.py)
The three steps are basically methods of Mooc object defined in mooc.py. The first step is to parse the JSON. The JSON contains the blocks that are contained in the course. The parse_json method makes objects of various types of supported xblocks (defined in openedx2zim/xblocks_extractor), and makes the folder tree.

Now, the annexe step gets all the pages of the course and it creates the HTML content. (I still need to determine exact things in more detail here.Mostly done in openedx2zim/annexe.py)

The third step is to download the content. Firstly the content of the main page is downloaded and then we download the content for each xblock through the defined functions in the specific xblock_extractor class. Each xblock_extractor class should look like as follows - https://github.com/openzim/openedx/blob/master/openedxtozim/xblocks_extractor/xblocks.example

We then render the pages using the render functions in annexe.py. The scraper is far more complex than the simple explanation that I've made here and I'll update this once I dig up more details. I tried to create a ZIM but couldn't due to network issues (hopefully will do one today). Also, I found out that the parse step takes quite long as there are many folders to be created in the forums. I think it makes sense if we could create multiple ZIMs for multiple versions like course, course + forum, course + wiki, course + forum + wiki (as everyone may not want everything).

**Comment by rgaudin** [comment]
Thank you for this introduction. Could you expand a bit on the following points:

* What are all those features you mention (Wiki, Forum). Are there more? Is it open for all students?
* Can you list the known xbocks and which are supported ATM?
* The ZIP you shared only contains an `xblocks.json` itself only containing `{"success": "The state of this problem has changed since you loaded this page. Please refresh your page."}`
* Can you share the structure of the JSON we get?
* You mentioned a folder tree ; can you elaborate?
* Are we downloading any HTML (the homepage sentence is unclear) or only from JSON?
* Noticed we have a video-related option (reencoding). Are videos hosted on openedx instance ?
* More details on Annexe step obviously.
* What kind of transformation are we doing to content (pages)
* Are we optimizing media beside transcoding videos to webm?

Thank you ; as discussed, in a separate thread, an overview of the code base limitations and proposed refactoring would also help.

**Comment by satyamtg** [comment]
> * The ZIP you shared only contains an `xblocks.json` itself only containing `{"success": "The state of this problem has changed since you loaded this page. Please refresh your page."}`

I uploaded the wrong file. I've corrected that. We now have 2 JSON files - one with course info and other with course blocks (prettified version)

> * Can you share the structure of the JSON we get?

Actually, that depends upon the type of request we send to the server. There are different requests by different xblocks_extractors too. However, we do get all xblocks of a course firstly and that's in the ZIP.

> * Noticed we have a video-related option (reencoding). Are videos hosted on openedx instance ?

Sometimes yes, sometimes no. The scraper does support videos hosted on YouTube so this needs me to find a course with that feature to test.

> * Are we optimizing media beside transcoding videos to webm?

Yes. Images are being optimized.

**Comment by dattaz** [comment]
>     * Can you list the known xbocks and which are supported ATM?

https://openedx.atlassian.net/wiki/spaces/COMM/pages/43385346/XBlocks+Directory

List of supported xblocks are here : https://github.com/openzim/openedx/tree/master/openedxtozim/xblocks_extractor , but i think we must check current status of each.

>     * You mentioned a folder tree ; can you elaborate?

It's something to navigate inside mooc, like on the website, here a capture from edx (not from a zim, but the idea is the same)
![2020-06-26_17-44](https://user-images.githubusercontent.com/6572195/85875681-e15ade80-b7d4-11ea-8d79-7fff6a2aa568.png)


>     * Are we downloading any HTML (the homepage sentence is unclear) or only from JSON?
Yes we download HTML (and we have a xblocks HTML). For homepage, we download and extract only "message" part from mooc homepage. (cf https://github.com/openzim/openedx/blob/master/openedxtozim/mooc.py#L244)

>    The scraper does support videos hosted on YouTube so this needs me to find a course with that feature to test.
 These courses use youtube video, I don't know if you can still enroll, or maybe in the new version?
https://courses.edx.org/courses/course-v1:Microsoft+DEV274x+1T2018a/course/
https://courses.edx.org/courses/course-v1:MandarinX+MX501x+2T2018/
https://courseware.epfl.ch/courses/course-v1:EPFL+species-conservation+2018_T2/course/

**Comment by satyamtg** [comment]
> * What kind of transformation are we doing to content (pages)

We basically leave the transformation to the xblocks_extractors. Each xblocks_extractor is basically a class by the same name as that of the xblock. It has 3 methods - 
1. init() - To initialize the class. Each xblock holds a reference to it's parent
2. download() - This is basically a place where we do anything to download the content. Say for a video xblock, we go to the xblock URL, scrape its content via beautifulsoup, download the video to the specific path (the folder tree), and extract descriptions etc.
3. render() - This returns HTML content that we can include in the vertical xblock for rendering. Basically, its a custom template that we prepare, and put all the scraped data in.

In the first step in mooc.py, we create objects of these classes (by looking at the particular xblock in the JSON).

**Comment by rgaudin** [comment]
Thanks!

**Comment by satyamtg** [comment]
Talking about the current scraper state, we have support for most of the important xblocks (the most frequently used ones). However, after a bit of searching I've found the following two resources for the list of xblocks. [This](https://github.com/Livit/Livit.Learn.EdX/wiki/List-of-XBlocks) is a list of xblocks used by livit (though I do not know much about livit). Also, a better documentation on the list of xblocks can be found [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/43385346/XBlocks+Directory). For xblocks supported by edX, they are basically be found [here](https://github.com/edx-solutions?q=xblock&type=&language=) and [here](https://github.com/edx?q=xblock&type=&language=).

**Comment by rgaudin** [comment]
Thanks for the update
