### ISSUE TITLE
automatically unwrap current chapter in course side nav 

### ISSUE THREAD

**Issue by dattaz** [openzim/openedx#5]
- [ ] add  class="active" to active li chapter in course menu

- [ ] also add class ".in" and set aria-expanded="true" to related a tag

You can find some explanation here: https://bootstrapious.com/p/bootstrap-sidebar

**Comment by dattaz** [comment]
The file to modify is openedx/templates/menu.html
You need to had a test like {% if vertical and chapter["folder_id"] == vertical["folder_id"] %}

If you need help post a comment or ask on irc (dattaz/#kiwix in freenode)

**Comment by lokeshshastrakar** [comment]
hey dattaz, how can I test it on windows

**Comment by dattaz** [comment]
You can't easily....I'll try for you.
(If you really want i can explain but it's waste of time IMO, because you haven't cached content)
