### ISSUE TITLE
https://mooc.phzh.ch/ Wrong layout 

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#71]
On page "Intro and objectives" the top image seems to be at 90% width and much smaller height. Fonts are also incorrectly scrapped
![Capture d’écran 2020-07-20 à 10 22 31 (1)](https://user-images.githubusercontent.com/21675885/87917537-6c965f80-ca75-11ea-9805-4eda6854fec5.png)

**Comment by satyamtg** [comment]
As mentioned in https://github.com/openzim/openedx/issues/72#issuecomment-662921793, this might be fixed with a better portion to scrape. I'm working on that.
