### ISSUE TITLE
Wrong fonts and background in scrap of https://mooc.phzh.ch/

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#72]
In "intro and objectives" page the bottom text is in a Serif font. Black background does not extend to the whole text area.
![Capture d’écran 2020-07-20 à 10 31 39](https://user-images.githubusercontent.com/21675885/87916794-36a4ab80-ca74-11ea-91ac-be237573e9ba.png)

**Comment by satyamtg** [comment]
Fonts are not scraped at the moment properly. For the black background not extending, it may be due to wrong div being scraped. I have taken a look at several MOOCs and there's a div with class xblock that seems common everywhere. I think we can scrape that instead.
