### ISSUE TITLE
Video should be centered with 100% width in https://mooc.phzh.ch/ ZIM

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#73]
It's currently aligned to the left and smaller than 100% width that is seen in the original MOOC.
![Capture d’écran 2020-07-20 à 10 33 39](https://user-images.githubusercontent.com/21675885/87916964-7ec3ce00-ca74-11ea-8658-49db8d1dd12c.png)

**Comment by satyamtg** [comment]
Centering the video sounds reasonable here. But, since we optimize the videos, we drop its resolution quite a bit. So, if we chose to have videos take 100% width forcefully, it would definitely make that look blurry. @rgaudin @Popolechien what are your suggestions?

**Comment by rgaudin** [comment]
Yes it definitely would. But only when using (`--low-quality` – which we'll always do).
I'd lean toward keeping it as it was online, as that what the course creator expected but I don't have any other argument.
It's important the course looks lean and consistent though.

**Comment by Popolechien** [comment]
Same here. Low quality on a very big screen would show, but a lot of use cases will be on tablets or smartphones in which case there's such a thing as too small but not too big (hopefully).

**Comment by rgaudin** [comment]
From the tests, only phzh has it centered.
