### ISSUE TITLE
Extra bulletpoints in https://mooc.phzh.ch/ ZIM file

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#74]
In Topic 1 This is me > Unit 1 About my person an extra set of bulletpoints appears next to bulletpoints:
![Capture d’écran 2020-07-20 à 10 34 50](https://user-images.githubusercontent.com/21675885/87917090-b29ef380-ca74-11ea-80aa-d27ff30e00d7.png)

**Comment by satyamtg** [comment]
This is because the xblock html that we scrape has them. The first one is the <li> bulletpoint and the second one is an image. Here's a screenshot of what the actual page looks from where we scrape
![Screenshot from 2020-07-22 15-17-10](https://user-images.githubusercontent.com/17774888/88162543-19680c80-cc2f-11ea-967e-8e46ff25702e.png)

**Comment by Popolechien** [comment]
Not what I see with Chrome on Mac. Could it be a Linux issue that carries into the zim?
![Capture d’écran 2020-07-22 à 12 03 21](https://user-images.githubusercontent.com/21675885/88163736-69d17100-cc13-11ea-96c2-1f3f452ba828.png)

**Comment by satyamtg** [comment]
> Not what I see with Chrome on Mac. Could it be a Linux issue that carries into the zim?
Did you see the course on the LMS or the xblock URL? The xblock URL is where we scrape from. This is the xblock URL - https://mooc.phzh.ch/xblock/block-v1:PHZH+W-IB+2019_E+type@html+block@3b7395bfc98247e581e5e5d3812c8eea

**Comment by rgaudin** [comment]
@Popolechien, there's one important information I think ; in Openedx, all *blocks* are available both within the learning flow (*Learning Management System*) and individually.
Both should be mostly identical but there might be differences.
The scraper fetches content from the individual view.

**Comment by Popolechien** [comment]
@satyamtg Ah yes in that case I see both bulletpoints.
