### ISSUE TITLE
Audio file from https://mooc.phzh.ch/ does not play

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#75]
In Step2 > Unit 3 there is an audio file where the user is shown an example of how to intoduce himself.

Basically if there is a "play" icon the user should expect to hear instructions and not download an mp3 file that they would have to open and later play.
Additionaly I get three different behaviours depending on whether I'm on Desktop (download), macOS (nothing) or JS (weird-ass code appears on screen), so I suspect it's a file format compatibility / platform issue.

**Comment by satyamtg** [comment]
This is indeed not difficult to fix as that's just an <a> link to an .mp3 file. We can do an audio player using videojs whenever we encounter this. Should also fix #76.
