### ISSUE TITLE
Missing icons in navigation bar

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#77]
As seen in https://mooc.phzh.ch/ but I would suspect it's for all OpenEDx ZIM files.

![Capture d’écran 2020-07-20 à 11 08 37](https://user-images.githubusercontent.com/21675885/87920432-78842080-ca79-11ea-973b-394218cd6464.png)

**Comment by satyamtg** [comment]
Are you talking about those question mark icons? They actually are valid icons and indicate that those tabs contain assessments. We can use a different icon though. We use fontawesome 5 for icons.

**Comment by Popolechien** [comment]
Ah no if it's an actual feature and not a bug, then it's one less ticket :-)
