### ISSUE TITLE
https://mooc.phzh.ch/ MOOC has navigation bar whereas source MOOC does not

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#78]
I'm speaking of the one on top of the page that is also described in #77 
![Capture d’écran 2020-07-20 à 11 08 37](https://user-images.githubusercontent.com/21675885/87920432-78842080-ca79-11ea-973b-394218cd6464.png)

**Comment by satyamtg** [comment]
As described in https://github.com/openzim/openedx/pull/92#issue-456779406 , in the current way that we follow, we try to get the CSS and JS from the instance at the vertical level and apply that to the course content. This navigation bar is an element on our side, though most of the instances have navigation bar, some like PHZH do not. I mean we can have this element as an optional element though. What do you suggest @rgaudin, @Popolechien ?

**Comment by rgaudin** [comment]
I don't understand the question. Is this bar a replacement of the regular left-side navigation? How is this phzh specific?

**Comment by satyamtg** [comment]
> I don't understand the question. Is this bar a replacement of the regular left-side navigation? How is this phzh specific?

No, this is not a replacement for the left-side navigation. The online and offline PHZH instances look as follows -
![Screenshot from 2020-08-05 14-30-39](https://user-images.githubusercontent.com/17774888/89393446-6f0ce080-d728-11ea-9630-a5aa1753a566.png)

Notice that the online version (right) does not have a top navigation bar (ignore icons on the left offline version as those appear in the ZIMs). However, this navbar is present in instances like edX. The thing is, in the offline version, this top bar is made by  the scraper and not scraped from the instance as we have HTMLs at the vertical level whereas instances have them at the sequential level.

**Comment by rgaudin** [comment]
OK, I understand now. I don't think it is a problem to have it while the online version does not.

@Popolechien if you think it's important that it's not present, we could add a parameter to optionalize this.

**Comment by Popolechien** [comment]
I will leave it for PHZH to decide probably, but if it's only adding a parameter then it's not much work and could be added (if not for this zim then for one of the next ones).
