### ISSUE TITLE
Input box is too small in https://mooc.phzh.ch/ ZIM

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#79]
Only 21 characters long whereas it should be 100% width (may be linked to #71?)
![Capture d’écran 2020-07-20 à 11 13 43](https://user-images.githubusercontent.com/21675885/87920911-2abbe800-ca7a-11ea-9736-57152500053b.png)

**Comment by satyamtg** [comment]
This is basically controlled by a jQuery script that doesn't seem to run at the moment.
