### ISSUE TITLE
Weird tag appears in text on https://mooc.phzh.ch/

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#80]
In Topic 1 - Unit 1 - Step 2 somewhere down `01-01-02` appears next to "Task 1"

![Capture d’écran 2020-07-20 à 11 22 25](https://user-images.githubusercontent.com/21675885/87921945-9488c180-ca7b-11ea-889a-9e10bdffd8df.png)

These numbers do not appear anywhere in the original 

![Capture d’écran 2020-07-20 à 11 24 45](https://user-images.githubusercontent.com/21675885/87922014-a9655500-ca7b-11ea-8ba6-45e08289914f.png)

**Comment by satyamtg** [comment]
This is due to the fact that we do have those on the xblock names in the JSON. That can be fixed by not taking the name from the JSON.
