### ISSUE TITLE
Segment title is shown when it should not

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#81]
In https://mooc.phzh.ch/ ZIM at each step the step number is indicated (with an extra large padding) 

![Capture d’écran 2020-07-20 à 11 27 54](https://user-images.githubusercontent.com/21675885/87922368-314b5f00-ca7c-11ea-94bd-6afff39052fa.png)

This Step number and padding do not appear in the original version:

![Capture d’écran 2020-07-20 à 11 29 09](https://user-images.githubusercontent.com/21675885/87922523-66f04800-ca7c-11ea-8268-3b30e6d19ac8.png)

**Comment by satyamtg** [comment]
This is rather a thing which we shall make optional as there are instances like edX which have this heading outside the vertical content block. So, it seems that we shall add a new boolean parameter, say --page-titles which would be passed to the scraper while running. What do you think @Popolechien @rgaudin ?

**Comment by Popolechien** [comment]
Well I have no preference but for the fact that when this section title is added there's also a bunch of blank space around it that is rather... unsightly.

**Comment by rgaudin** [comment]
Also think we could make the style of that title less space consuming and that would save us the complexity of a parameter for this.

**Comment by satyamtg** [comment]
> Also think we could make the style of that title less space consuming and that would save us the complexity of a parameter for this.

After the CSS and JS changes, right now the title looks something like this - 
![Screenshot from 2020-08-05 14-30-39](https://user-images.githubusercontent.com/17774888/89421493-c1162c00-d751-11ea-80dc-201a4c6ff6eb.png)

@rgaudin @Popolechien do we still want to change the appearance or leave it like that? (Apparently that space was due to the CSS and JS not applied properly)

**Comment by rgaudin** [comment]
OK for me

**Comment by Popolechien** [comment]
Looks good enough to me.

**Comment by satyamtg** [comment]
I think we can close this then.
