### ISSUE TITLE
Collapsible section is not collapsed / collapsable in https://mooc.phzh.ch/ ZIM 

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#82]
At the bottom of Topic 1 - Unit 1 - Step 3 there is a small section for discussion: part of the text is in a collapsible section (that expands or collapses when clicked on:
![image](https://user-images.githubusercontent.com/21675885/87923580-0530dd80-ca7e-11ea-9498-42d37b5b13e1.png)

In the ZIM file the section is permanently expanded
![Capture d’écran 2020-07-20 à 11 42 39](https://user-images.githubusercontent.com/21675885/87923669-21cd1580-ca7e-11ea-8e5c-450c83d14ea3.png)

**Comment by satyamtg** [comment]
Thats too because it's permanently expanded in xblock version - https://mooc.phzh.ch/xblock/block-v1:PHZH+W-IB+2019_E+type@sequential+block@386b0242c4ef47cda9af69240374b303. Just like https://github.com/openzim/openedx/issues/84#issuecomment-662984171
