### ISSUE TITLE
Confusing warning message for unsupported functionality in https://mooc.phzh.ch/ ZIM

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#83]
At the bottom of Topic 1 - Unit 1 - Step 3 there is a small section for discussion, followed by an area where users can post whatever comes through their mind and discuss.
![Capture d’écran 2020-07-20 à 11 45 01](https://user-images.githubusercontent.com/21675885/87923912-76709080-ca7e-11ea-8b6c-a599a4427563.png)

Because of the nature of a zim file the posts cannot be recorded and posted, and the section is replaced with a generic `This discussion is not supported, sorry!`
![Capture d’écran 2020-07-20 à 11 43 09](https://user-images.githubusercontent.com/21675885/87923952-82f4e900-ca7e-11ea-9d9e-859e8128ce0d.png)

However this is misleading / confusing because as far as the user is concerned a discussion _is_ supported (there are instructions to sit in a group, etc.). Not having a point of comparison, they do not know what they are looking at (or should be). A better alternative text would be `This functionality is not supported on offline platforms :-( `

**Comment by rgaudin** [comment]
It seems that reading is supported and contributing to the discussion is not. Am I right? In that case, we could either remove the message completely or specify clearly that it's read-only.

**Comment by satyamtg** [comment]
> It seems that reading is supported and contributing to the discussion is not. Am I right? In that case, we could either remove the message completely or specify clearly that it's read-only.

Yes, you're right. However, the screenshot in the first comment is of the online version and the warning message is as the discussion wasn't scraped as `--add-forum` wasn't passed while running. Maybe, we shall change the message to something like - "Discussions are not supported in this ZIM", or just remove that, and if there are discussions scraped but if those could not be supported, we might have a warning message.

**Comment by rgaudin** [comment]
Agrees
