### ISSUE TITLE
Incorrect display of tick boxes on 

### ISSUE THREAD

**Issue by Popolechien** [openzim/openedx#84]
In the Topic 1 - Unit 1 - Self-evaluation section, users are encouraged to tick boxes to evaluate their progress:
![Capture d’écran 2020-07-20 à 11 50 09](https://user-images.githubusercontent.com/21675885/87924516-4c6b9e00-ca7f-11ea-83f8-ffa750638662.png)

The ZIM rendering is entirely different (related to #71 maybe)
![Capture d’écran 2020-07-20 à 11 50 14](https://user-images.githubusercontent.com/21675885/87924570-5beae700-ca7f-11ea-9acb-5a1c002ea9a9.png)

**Comment by satyamtg** [comment]
Unlike the LMS view, the xblock URLs for self evaluations are generic xblocks with no added CSS. So, if we want the CSS, we would need to scrape the LMS views, which would be quite different for different instances as compared to xblocks individually (which are quite similar across instances). Here's  a xblock URL that you can see - https://mooc.phzh.ch/xblock/block-v1:PHZH+W-IB+2019_E+type@vertical+block@e516e0c129184e019b24710eb7ddc703 . The LMS URL for the same is https://mooc.phzh.ch/courses/course-v1:PHZH+W-IB+2019_E/jump_to/block-v1:PHZH+W-IB+2019_E+type@vertical+block@e516e0c129184e019b24710eb7ddc703 (must be enrolled to see these links).

If we try to have styling for this, by scraping the LMS web view, we would probably need to change the behaviour of the scraper and implement code for different instances to be scraped differently. @Popolechien @rgaudin @kelson42 @dattaz what do you suggest?

**Comment by Popolechien** [comment]
Currently time is of the essence so I'd favour leaving it as it is, but out of curiosity would you be able to estimate how much work would be needed to implemented scraping of LMS view?

Alternatively, I see a lot of tickets are related to grabbing the CSS (or not). Should we do a bit of code to grab it, wouldn't it solve many other tickets, and would that code be reusable with other MOOCs?
